spring.application.name=Backend
spring.datasource.url=jdbc:postgresql://localhost:5432/labo
spring.datasource.username=postgres
spring.datasource.password=PackCode*503
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
